# SPDX-License-Identifier: GPL-3.0-only

- name: reload systemctl
  become: true
  become_user: "{{ container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    daemon_reload: true
    scope: "{{ podman_systemd_scope }}"

- name: start service
  become: true
  become_user: "{{ container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ podman_service_name }}"
    scope: "{{ podman_systemd_scope }}"
    state: started

- name: restart service
  become: true
  become_user: "{{ container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ podman_service_name }}"
    scope: "{{ podman_systemd_scope }}"
    state: restarted

- name: enable service
  become: true
  become_user: "{{ container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ podman_service_name }}"
    enabled: true
    scope: "{{ podman_systemd_scope }}"
